# Gunakan image Nginx sebagai base image
FROM nginx:alpine

# Salin file index.html ke direktori yang sesuai
COPY index.html /usr/share/nginx/html/index.html

# Ekspose port 8081
EXPOSE 8081

